<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [15]:
import numpy as np
from datetime import *

In [10]:
nf = np.zeros((10))
nf

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
for n in range(2,100,2):
    nf[0:9]=nf[1:10]
    nf[-1] = n
    print(nf)

[0. 0. 0. 0. 0. 2. 4. 6. 8. 2.]
[0. 0. 0. 0. 2. 4. 6. 8. 2. 4.]
[0. 0. 0. 2. 4. 6. 8. 2. 4. 6.]
[0. 0. 2. 4. 6. 8. 2. 4. 6. 8.]
[ 0.  2.  4.  6.  8.  2.  4.  6.  8. 10.]
[ 2.  4.  6.  8.  2.  4.  6.  8. 10. 12.]
[ 4.  6.  8.  2.  4.  6.  8. 10. 12. 14.]
[ 6.  8.  2.  4.  6.  8. 10. 12. 14. 16.]
[ 8.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[ 4.  6.  8. 10. 12. 14. 16. 18. 20. 22.]
[ 6.  8. 10. 12. 14. 16. 18. 20. 22. 24.]
[ 8. 10. 12. 14. 16. 18. 20. 22. 24. 26.]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]
[12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]
[14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
[16. 18. 20. 22. 24. 26. 28. 30. 32. 34.]
[18. 20. 22. 24. 26. 28. 30. 32. 34. 36.]
[20. 22. 24. 26. 28. 30. 32. 34. 36. 38.]
[22. 24. 26. 28. 30. 32. 34. 36. 38. 40.]
[24. 26. 28. 30. 32. 34. 36. 38. 40. 42.]
[26. 28. 30. 32. 34. 36. 38. 40. 42. 44.]
[28. 30. 32. 34. 36. 38. 40. 42. 44. 46.]
[30. 32. 34. 36. 38. 40. 42. 44. 46. 48.]
[32. 34. 36. 38. 40. 42. 44. 46.

In [8]:
nf


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 10])

In [16]:
today = datetime.now().date()

In [21]:
startDate = (today - timedelta(10)).strftime('%Y-%m-%d')  

In [27]:
ss =today- timedelta(10)
ss

datetime.date(2018, 8, 7)

In [34]:
a = -1
if a:
    print("ss = True")
else:
    ss = False
    print('ss = False')
    

ss = True
